config/routes.rb
Gemeinschaft4::Application.routes.draw do
	
  	resources :ldap_import_sessions

	resources :network_settings
	
	resources :configurations
	
	resources :global_contacts do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :personal_contacts do
		member do
			get 'confirm_destroy'
		end
	end
		
	resources :call_logs do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :call_queues do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :call_forwards do  #OPTIMIZE Nest this inside sip_accounts and adjust the views accordingly.
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :conferences do
		member do
			get 'confirm_destroy'
		end
	end
	
	get "setup/index"  #OPTIMIZE Is this route being used?
	get "setup/create"  #OPTIMIZE Is this route being used?
	get "setup/new"  #OPTIMIZE Is this route being used?
	
	match '/auth/:provider/callback' => 'authentications#create'
	resources :authentications      , :only => [ :index, :create, :destroy ]
	
	devise_for :users, :controllers => {
		:sessions   => 'devise/sessions',
		:passwords  => 'passwords',
	}
	
	resources :sip_accounts do
		resources :extensions
	end
	resources :conferences do
		resources :extensions
	end
	resources :call_queues do
		resources :extensions
	end
	resources :backups, :only => [ :index, :create, :update, :show, :destroy, :new ]
	
	resources :sip_servers          , :only => [ :index, :show, :new, :create, :destroy ] do
		member do
			get 'confirm_destroy'
		end
	end
	resources :sip_proxies          , :only => [ :index, :show, :new, :create, :destroy ] do
		member do
			get 'confirm_destroy'
		end
	end
	resources :nodes                , :only => [ :index, :show ] # for now
	resources :voicemail_servers do
		member do
			get 'confirm_destroy'
		end
	end	
	
	resources :extensions do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :admin                , :only => [ :index ]
	resources :cdrs                 , :only => [ :index ]
	resources :kamailio             , :only => [ :index ], :format => 'txt'  #OPTIMIZE Is this route being used?
  
  match '/help',
		:via        => [ :get ],
		:controller => :home,
		:action     => 'help'

	match '/admin/help',
		:via        => [ :get ],
		:controller => :admin,
		:action     => 'help'
	
	match '/admin/shutdown',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :shutdown
	
	match '/admin/reboot',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :reboot
	
	match '/admin/confirm_reboot',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :confirm_reboot
	
	match '/admin/confirm_shutdown',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :confirm_shutdown
	
	match '/freeswitch-directory-entries/search',
		:via        => [ :get, :post ],
		:controller => :freeswitch_directory_entries,
		:action     => 'search',
		:format     => :'xml'
	
	match '/freeswitch-call-processing/actions((.:subfmt).:format)',
		:via        => [ :get, :post ],
		:controller => :freeswitch_call_processing,
		:action     => 'actions',
		:defaults    => { :format => :'xml', :subfmt => nil },
		:constraints => { :format => /[a-z0-9]+/, :subfmt => /[a-z0-9]+/ }
	
	match '/freeswitch-configuration/freeswitch',
		:via        => [ :get, :post ],
		:controller => :freeswitch_configuration,
		:action     => 'load',
		:format     => :'xml'
	
	resources :dialplan_routes, :path => 'dialplan-routes' do
		member do
			post :move_up
			post :move_down
			post :move_to_top
			post :move_to_bottom
			get 'confirm_destroy'
		end
		collection do
			get  :test
			post :test
		end
	end
	
	resources :dialplan_patterns, :path => 'dialplan-patterns' do
		member do
			get 'confirm_destroy'
		end
	end
	
	namespace :admin do
		resources :wizard_phone_and_user, :only => [:new, :create]
		resources :users do
			member do
				get 'confirm_destroy'
			end
		end
		resources :setup  #OPTIMIZE Do we need a full resource or just an index?
	end
	
	match '/admin/mail_configuration',
		:via        => [ :get ],
		:controller => 'admin/mail_configuration',
		:action     => :edit
	
	match '/admin/mail_configuration',
		:via        => [ :post ],
		:controller => 'admin/mail_configuration',
		:action     => :create
	
	match '/admin/mail_configuration/show',
		:via        => [ :get ],
		:controller => 'admin/mail_configuration',
		:action     => :show
	
	resources :reboot_requests, :only => [:index, :show, :create, :new ]  #OPTIMIZE Is this route being used?
	
	resources :manufacturer_snom    , :only => [ :index ]
	resources :manufacturer_aastra  , :only => [ :index ]  #OPTIMIZE Is this route being used?
	resources :manufacturer_tiptel  , :only => [ :index ]  #OPTIMIZE Is this route being used?
	
	match '/manufacturer_snom/:mac_address/:action',
		:via        => [ :get, :post ],
		:controller => :manufacturer_snom,
		:format     => :'xml'
	
	match '/manufacturer_snom/:mac_address/:sip_account/:action',
		:via        => [ :get, :post ],
		:controller => :manufacturer_snom,
		:format     => :'xml'
	
	match 'settings-:mac_address' => 'manufacturer_snom#show',
		:format => 'xml',
		:constraints => { :mac_address => /000413.*/ }
	
	match 'freeswitch-missed-call-:uuid' => 'freeswitch_call_log#set_missed_call'
	resources :freeswitch_call_log    , :only => [ :set_missed_call ]
	
	resources :provisioning_log_entries, :only => [ :index, :show ]  #OPTIMIZE Is this route being used?
	resources :phone_model_mac_addresses  #OPTIMIZE Is this route being used?
	match 'phones/:id/reboot' => 'phones#reboot', :as => :phone_reboot
	
	
	resources :phones do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :phones do
		resources :sip_accounts  #OPTIMIZE Is it still useful to nest sip_accounts in phones?
	end
	
	resources :sip_accounts do
		resources :phone_keys  #OPTIMIZE Is this route being used?
	end
	
	resources :sip_accounts do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :codecs  #OPTIMIZE Is this route being used?
	
	resources :sip_account_codecs  #OPTIMIZE Is this route being used?
	
	resources :phone_key_function_definitions  #OPTIMIZE Is this route being used?
	
	resources :phone_model_keys  #OPTIMIZE Is this route being used?
	
	resources :manufacturers do
		resources :phone_models
	end
	
	resources :phone_models do
		resources :phones
	end
	
	resources :fax_documents do
		member do
			get 'confirm_destroy'
			get 'number'
			put 'transfer'
			post 'update'
		end
	end
	
	resources :voicemails do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :sip_gateways, :path => 'gateways' do
		member do
			get 'confirm_destroy'
		end
	end
	
	match 'pin_change',
		:via        => [ :get ],
		:controller => :pin_change,
		:action     => :edit
	
	match 'pin_change',
		:via        => [ :post ],
		:controller => :pin_change,
		:action     => :update
	
	
	
	
	
	
	
	
	
	
	root :to => 'home#index'
	
	
end

app/views/admin/_welcome.de.html.erb
<h1>Willkommen bei Gemeinschaft 4.0</h1>
<div class="help_overview" style="font-size: 1em;">
	
	<p>
		Sie haben vor
		<%= time_ago_in_words( User.first.created_at ).gsub(/eine /,'einer ').gsub(/ein /,'einem ').gsub(/Tage/,'Tagen') %>
		die VoIP-Telefonanlage Gemeinschaft 4.0 erfolgreich
		installiert. Hier ein paar Tipps zum schnellen Einstieg:
	</p>
	<p>
		Ein neues Telefon muss dem System per MAC-Adresse
		bekanntgegeben werden. Für die einfacherere
		Administration stellen wir Ihnen dafür die zwei
		Assistenten
		„<%= link_to( "#{t(:wizard_phone_new)}",
			url_for( :controller => '/admin/wizard_phone_and_user', :action => 'new' )
		) %>“
		und
		„<%= link_to( "#{t(:wizard_phone_and_user_new)}",
			url_for( :controller => '/admin/wizard_phone_and_user', :action => 'new', :with_user => true )
		) %>“
		zur Verfügung.
	</p>
	
	<% phone_models = (PhoneModel.order(:name) || []).to_a %>
	<p>
		Aktuell werden folgende Telefone unterstützt: <%
		j = { phone_models.first => "", phone_models.last => " und " };
		phone_models.each{ |m| %><%= j[m] || ", " %>
		<%= link_to( m.name, m ) %><% } %>.
	</p>
	
	<p>
		Bitte achten Sie darauf, auf den Telefonen die
		<strong>aktuell stabile Firmware</strong> zu
		installieren.
		Bei den
		<%= link_to "Telefon-Modellen", phone_models_path %>
		finden Sie einen Link zur jeweiligen Online-Doku.
	</p>
	<p>
		Bitte verfolgen Sie den Twitter-Account
		<%= link_to '@GemeinschaftPBX', 'http://twitter.com/GemeinschaftPBX' %>
		für Updates und Informationen zu Gemeinschaft.
	</p>
	<p>
		<strong>Nächster Schritt:</strong>
		<%= link_to( "#{t(:wizard_phone_new)}",
			url_for(:controller => '/admin/wizard_phone_and_user', :action => 'new')
		) %>
	</p>
	
	<h2>Support</h2>
	<p>
		Gemeinschaft ist ein Produkt der
		<%= link_to "AMOOMA GmbH", 'http://www.amooma.de' %>,
		die auch kommerziellen Support und Consulting dazu anbietet.
		Zusätzlich gibt es eine kostenlose Mailingliste unter<br />
		<%= link_to(
			'http://groups.google.com/group/gemeinschaft-users',
			'http://groups.google.com/group/gemeinschaft-users'
		) %>
	</p>
	
</div>

app/views/admin/_welcome.html.erb
<h1>Welcome to Gemeinschaft 4.0</h1>
<div class="help_overview" style="font-size: 1em;">
	
	<p>
		You installed Gemeinschaft
		<%= time_ago_in_words( User.first.created_at ) %> ago.
		Quick start tips:
	</p>
	<p>
		Use
		“<%= link_to( "#{t(:wizard_phone_new)}",
			url_for( :controller => '/admin/wizard_phone_and_user', :action => 'new' )
		) %>”
		or
		“<%= link_to( "#{t(:wizard_phone_and_user_new)}",
			url_for( :controller => '/admin/wizard_phone_and_user', :action => 'new', :with_user => true )
		) %>”
		to set-up new phones.
	</p>
	
	<% phone_models = (PhoneModel.order(:name) || []).to_a %>
	<p>
		We support the following phone models: <%
		j = { phone_models.first => "", phone_models.last => " and " };
		phone_models.each{ |m| %><%= j[m] || ", " %>
		<%= link_to( m.name, m ) %><% } %>.
	</p>
	
	<p>
		Please use the <strong>latest stable firmware</strong> on
		the phones.
	</p>
	<p>
		Please follow the Twitter account
		<%= link_to '@GemeinschaftPBX', 'http://twitter.com/GemeinschaftPBX' %>
		for updates.
	</p>
	<p>
		<strong>Next step:</strong>
		<%= link_to( "#{t(:wizard_phone_new)}",
			url_for(:controller => '/admin/wizard_phone_and_user', :action => 'new')
		) %>
	</p>
    
    <h2>Support</h2>
    <p>
    	Gemeinschaft is an
    	<%= link_to "AMOOMA GmbH", 'http://www.amooma.de' %>
    	product. We provide commerical support and consulting for
    	Gemeinschaft. In addition you'll find free support at the
    	following mailing-list:<br />
    	<%= link_to(
    		'http://groups.google.com/group/gemeinschaft-users',
    		'http://groups.google.com/group/gemeinschaft-users'
    	) %>
    </p>
	
</div>

app/views/admin/confirm_reboot.erb
<h2><%=
	link_to( t(:reboot_system),
		url_for(:controller => '/admin', :action => 'reboot')
	)
	%> <%=
	link_to( t(:cancel),
		url_for(:controller => '/admin', :action => 'index')
	)
%></h2>

app/views/admin/confirm_shutdown.erb
<h2><%=
	link_to( t(:shutdown),
		url_for(:controller => '/admin', :action => 'shutdown')
	)
	%> <%=
	link_to( t(:cancel),
		url_for(:controller => '/admin', :action => 'index')
	)
%></h2>

app/views/admin/help.html.erb
<h1>Admin tasks</h1>

<div class="help_overview">
	
	<section>
		<h2>Call Forwards</h2>
		<p><em>How do I configure a call forward for a SIP account?</em></p>
		<p>
			Go to the <%= link_to( "Call Forwards",
				url_for(:controller => '/call_forwards', :action => 'index')) %>
			and click <q>New</q> or <q>Edit</q>.
		</p>
		<ul>
			<li>Select a SIP account, a case (always / busy / noanswer /
				offline / assistant) enter a destination, and make it
				active.</li>
			<li>Leave the source blank for calls from any number
				or fill out the source if you want a call forward
				that is valid for calls from a specific source only.</li>
			<li>Leave the destination blank, if you want to
				<q>blacklist</q> a source.</li>
			<li>Timeout must be set if case is <q>noanswer</q>.</li>
			<li>For your voicemail box set <q>voicemail</q> as destination.</li>
		</ul>
	</section>
	
	<section>
		<h2>Queue Login/Logout</h2>
		<p><em>How do I log in to a queue?</em></p>
		<ul>
			<li>To log in to a queue dial <code>*50*</code> and the extension
				of the queue.</li>
			<li>To log out dial <code>#50#</code> and the extension
				of the queue.</li>
		</ul>
	</section>

	<section>
		<h2>Fax</h2>
		<p><em>How can I define a number to receive a fax?</em></p>
		<p>
			Go to the <%= link_to( "Extensions",
				url_for(:controller => '/extensions', :action => 'index')) %>
			and click <q>New</q> or <q>Edit</q>.
		</p>
		<ul>
			<li>Fill out <q>Extension</q> with the number of your choice.</li>
			<li>Use <q>-fax-receive-</q> as target.</li>
		</ul>
	</section>
	
</div>

app/views/admin/index.html.erb
<%= render 'admin/welcome' if Phone.count == 0 && User.count < 2 %>

<div class="index_overview">
	
	<section>
		<h2><%= t(:wizards) %></h2>
		<ul>
			<li><%= link_to( "#{t(:wizard_phone_new)}",
				url_for(:controller => '/admin/wizard_phone_and_user', :action => 'new')
			) %></li>
			<li><%= link_to( "#{t(:wizard_phone_and_user_new)}",
				url_for(:controller => '/admin/wizard_phone_and_user', :action => 'new', :with_user => true)
			) %></li>
		</ul>
	</section>
	
</div>


<hr />
<% if @phones && ! @phones.empty? %>
	<h2><%= t(:listing_phones_last_modified) %></h2>
	
	<%= render :partial => 'phones/table_of_phones', :locals => {:phones => @phones} %>
	
	<p>
	<%= link_to( t(:list_all_phones), url_for(:controller => '/phones', :action => 'index')) if @number_of_phones > @phones.length %>
	</p>
<% end %>

app/views/admin/reboot.erb
<h1><%= t(:reboot_initiated) %></h1>

app/views/admin/shutdown.erb
<h1><%= t(:shutdown_initiated) %></h1>