config/routes.rb
Gemeinschaft4::Application.routes.draw do
	
  	resources :ldap_import_sessions

	resources :network_settings
	
	resources :configurations
	
	resources :global_contacts do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :personal_contacts do
		member do
			get 'confirm_destroy'
		end
	end
		
	resources :call_logs do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :call_queues do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :call_forwards do  #OPTIMIZE Nest this inside sip_accounts and adjust the views accordingly.
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :conferences do
		member do
			get 'confirm_destroy'
		end
	end
	
	get "setup/index"  #OPTIMIZE Is this route being used?
	get "setup/create"  #OPTIMIZE Is this route being used?
	get "setup/new"  #OPTIMIZE Is this route being used?
	
	match '/auth/:provider/callback' => 'authentications#create'
	resources :authentications      , :only => [ :index, :create, :destroy ]
	
	devise_for :users, :controllers => {
		:sessions   => 'devise/sessions',
		:passwords  => 'passwords',
	}
	
	resources :sip_accounts do
		resources :extensions
	end
	resources :conferences do
		resources :extensions
	end
	resources :call_queues do
		resources :extensions
	end
	resources :backups, :only => [ :index, :create, :update, :show, :destroy, :new ]
	
	resources :sip_servers          , :only => [ :index, :show, :new, :create, :destroy ] do
		member do
			get 'confirm_destroy'
		end
	end
	resources :sip_proxies          , :only => [ :index, :show, :new, :create, :destroy ] do
		member do
			get 'confirm_destroy'
		end
	end
	resources :nodes                , :only => [ :index, :show ] # for now
	resources :voicemail_servers do
		member do
			get 'confirm_destroy'
		end
	end	
	
	resources :extensions do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :admin                , :only => [ :index ]
	resources :cdrs                 , :only => [ :index ]
	resources :kamailio             , :only => [ :index ], :format => 'txt'  #OPTIMIZE Is this route being used?
  
  match '/help',
		:via        => [ :get ],
		:controller => :home,
		:action     => 'help'

	match '/admin/help',
		:via        => [ :get ],
		:controller => :admin,
		:action     => 'help'
	
	match '/admin/shutdown',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :shutdown
	
	match '/admin/reboot',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :reboot
	
	match '/admin/confirm_reboot',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :confirm_reboot
	
	match '/admin/confirm_shutdown',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :confirm_shutdown
	
	match '/freeswitch-directory-entries/search',
		:via        => [ :get, :post ],
		:controller => :freeswitch_directory_entries,
		:action     => 'search',
		:format     => :'xml'
	
	match '/freeswitch-call-processing/actions((.:subfmt).:format)',
		:via        => [ :get, :post ],
		:controller => :freeswitch_call_processing,
		:action     => 'actions',
		:defaults    => { :format => :'xml', :subfmt => nil },
		:constraints => { :format => /[a-z0-9]+/, :subfmt => /[a-z0-9]+/ }
	
	match '/freeswitch-configuration/freeswitch',
		:via        => [ :get, :post ],
		:controller => :freeswitch_configuration,
		:action     => 'load',
		:format     => :'xml'
	
	resources :dialplan_routes, :path => 'dialplan-routes' do
		member do
			post :move_up
			post :move_down
			post :move_to_top
			post :move_to_bottom
			get 'confirm_destroy'
		end
		collection do
			get  :test
			post :test
		end
	end
	
	resources :dialplan_patterns, :path => 'dialplan-patterns' do
		member do
			get 'confirm_destroy'
		end
	end
	
	namespace :admin do
		resources :wizard_phone_and_user, :only => [:new, :create]
		resources :users do
			member do
				get 'confirm_destroy'
			end
		end
		resources :setup  #OPTIMIZE Do we need a full resource or just an index?
	end
	
	match '/admin/mail_configuration',
		:via        => [ :get ],
		:controller => 'admin/mail_configuration',
		:action     => :edit
	
	match '/admin/mail_configuration',
		:via        => [ :post ],
		:controller => 'admin/mail_configuration',
		:action     => :create
	
	match '/admin/mail_configuration/show',
		:via        => [ :get ],
		:controller => 'admin/mail_configuration',
		:action     => :show
	
	resources :reboot_requests, :only => [:index, :show, :create, :new ]  #OPTIMIZE Is this route being used?
	
	resources :manufacturer_snom    , :only => [ :index ]
	resources :manufacturer_aastra  , :only => [ :index ]  #OPTIMIZE Is this route being used?
	resources :manufacturer_tiptel  , :only => [ :index ]  #OPTIMIZE Is this route being used?
	
	match '/manufacturer_snom/:mac_address/:action',
		:via        => [ :get, :post ],
		:controller => :manufacturer_snom,
		:format     => :'xml'
	
	match '/manufacturer_snom/:mac_address/:sip_account/:action',
		:via        => [ :get, :post ],
		:controller => :manufacturer_snom,
		:format     => :'xml'
	
	match 'settings-:mac_address' => 'manufacturer_snom#show',
		:format => 'xml',
		:constraints => { :mac_address => /000413.*/ }
	
	match 'freeswitch-missed-call-:uuid' => 'freeswitch_call_log#set_missed_call'
	resources :freeswitch_call_log    , :only => [ :set_missed_call ]
	
	resources :provisioning_log_entries, :only => [ :index, :show ]  #OPTIMIZE Is this route being used?
	resources :phone_model_mac_addresses  #OPTIMIZE Is this route being used?
	match 'phones/:id/reboot' => 'phones#reboot', :as => :phone_reboot
	
	
	resources :phones do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :phones do
		resources :sip_accounts  #OPTIMIZE Is it still useful to nest sip_accounts in phones?
	end
	
	resources :sip_accounts do
		resources :phone_keys  #OPTIMIZE Is this route being used?
	end
	
	resources :sip_accounts do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :codecs  #OPTIMIZE Is this route being used?
	
	resources :sip_account_codecs  #OPTIMIZE Is this route being used?
	
	resources :phone_key_function_definitions  #OPTIMIZE Is this route being used?
	
	resources :phone_model_keys  #OPTIMIZE Is this route being used?
	
	resources :manufacturers do
		resources :phone_models
	end
	
	resources :phone_models do
		resources :phones
	end
	
	resources :fax_documents do
		member do
			get 'confirm_destroy'
			get 'number'
			put 'transfer'
			post 'update'
		end
	end
	
	resources :voicemails do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :sip_gateways, :path => 'gateways' do
		member do
			get 'confirm_destroy'
		end
	end
	
	match 'pin_change',
		:via        => [ :get ],
		:controller => :pin_change,
		:action     => :edit
	
	match 'pin_change',
		:via        => [ :post ],
		:controller => :pin_change,
		:action     => :update
	
	
	
	
	
	
	
	
	
	
	root :to => 'home#index'
	
	
end

app/models/sip_account.rb
class SipAccount < ActiveRecord::Base
  
  belongs_to :sip_server       , :validate => true
  belongs_to :sip_proxy        , :validate => true
  belongs_to :voicemail_server , :validate => true
  belongs_to :phone            , :validate => true
  belongs_to :user             , :validate => true
  has_many :call_forwards, :dependent => :destroy
  has_many :call_logs, :dependent => :destroy
  has_many :sip_account_to_extensions, :dependent => :destroy   #OPTIMIZE :order => 'position' ?
  has_many :extensions, :through => :sip_account_to_extensions  #OPTIMIZE :order => 'position' ?
  has_many :call_forwards, :dependent => :destroy
  acts_as_list :scope => :user
  
  accepts_nested_attributes_for :extensions, :user
  
  validate_username         :auth_name
  validates_uniqueness_of   :auth_name, :case_sensitive => false, :scope => :sip_server_id
  # As long as caller_name stays here
  validates_presence_of     :caller_name
  validates_presence_of     :sip_server
  validates_presence_of     :sip_proxy
  validates_presence_of     :voicemail_server , :if => Proc.new { |me| me.voicemail_server_id }
  validates_presence_of     :phone            , :if => Proc.new { |me| me.phone_id }
  validates_presence_of     :user             , :if => Proc.new { |me| me.user_id }
  
  validate {
    if self.user
      if ! Ability.new( self.user ).can?( :have, SipAccount )
        errors.add( :user, I18n.t( :sip_account_user_cant_have_sip_accounts ))
      end
    end
  }
  
  validate_password         :password
  
  validates_numericality_of :voicemail_pin,
    :if => Proc.new { |sip_account| ! sip_account.voicemail_server_id.blank? },
    :only_integer => true,
    :greater_than_or_equal_to => 1000,
    :message => I18n.t(:numeric_greater_than, :value => 1000)
  validates_inclusion_of    :voicemail_pin,
    :in => [ nil ],
    :if => Proc.new { |sip_account| sip_account.voicemail_server_id.blank? },
    :message => I18n.t(:must_not_be_set_if_no_voicemail_server)
  
  after_validation :phone_reboot
  before_destroy   :phone_reboot
  
  before_validation( :on => :update ) {
    if self.auth_name != self.auth_name_was
      errors.add( :auth_name, I18n.t(:cannot_be_changed) )
    end
  }
  
  before_validation {
    if self.phone_id
      if self.user_id != nil
        if ! SipAccount.find(:all, :conditions => ['user_id != ? AND phone_id = ? ', "#{self.user_id}", "#{self.phone_id}"]).empty? \
        || ! SipAccount.where(:user_id => nil, :phone_id => self.phone_id).empty?
          errors.add( :base, I18n.t(:phone_belongs_to_user_already) )
        end
      else
        if ! SipAccount.find(:all, :conditions => ['user_id NOT ? AND phone_id = ?', nil, "#{self.phone_id}" ]).empty?
          errors.add( :base, I18n.t(:phone_belongs_to_user_already) )
        end
      end
    end
  }
  
  after_validation( :on => :create ) {
    if (self.sip_server) \
    && (self.sip_proxy) \
    && (self.sip_proxy.is_local)
      create_subscriber()
    end
  }
  
  after_validation( :on => :update ) {
    if (self.sip_server) \
    && (self.sip_proxy) \
    && (self.sip_proxy.is_local)
      update_subscriber()
    else
      delete_subscriber()
    end
  }
  
  before_destroy {
    delete_subscriber()
  }
  
  # Returns whether a SIP account is registered (in Kamailio).
  #
  def registered?
    return (
      Location.where({
        :username => "#{self.auth_name}",
        #:domain   => "...",  #OPTIMIZE Check domain.
      })
      .where( Location.arel_table[:contact].not_eq(nil) )
      .where( Location.arel_table[:contact].not_eq('') )
    ).first != nil
  end
  
  def phone_reboot
    self.phone.reboot if self.phone
  end
  
  def to_display
    return I18n.t(:sip_account_to_display, :id => self.id, :auth_name => self.auth_name, :caller_name => self.caller_name, :position => self.position, :realm => self.realm)
  end
  
  # Finds a call forwarding rule by reason and source.
  #
  def call_forwards_for( reason, source )
  (
    return nil if ! reason
	  
    [ source, '' ].each { |the_source|
      cfwd = (
        CallForward.where({
          :sip_account_id => self.id,
          :active         => true,
          :source         => the_source.to_s,
        })
        .joins( :call_forward_reason )
        .where( :call_forward_reasons => {
          :value => reason.to_s,
        })
        .first )
      
      if cfwd
        if cfwd.destination == "voicemail"
          cfwd.destination = "-vbox-#{auth_name}"
        end
        return cfwd
      end
    }
    
    return nil
  )end
  
  def voicemail_pin_confirmation
  end
  
  def voicemail_pin_old
  end
  
  private
  
  def create_subscriber()
    subscriber = Subscriber.create(
      :username   =>  self.auth_name,
      :domain     =>  self.sip_server.host,
      :password   =>  self.password,
      :ha1        =>  Digest::MD5.hexdigest( "#{self.auth_name}:#{self.sip_server.host}:#{self.password}" )
    )
    if ! subscriber.valid?
      errors.add( :base, I18n.t(:subscriber_not_created))
    end
  end
  
  def update_subscriber()
    subscriber_update = Subscriber.find_by_username( self.auth_name_was )
    if (! subscriber_update.nil?)
      subscriber = subscriber_update.update_attributes(
        :username   =>  self.auth_name,
        :domain     =>  self.sip_server.host,
        :password   =>  self.password,
        :ha1        =>  Digest::MD5.hexdigest( "#{self.auth_name}:#{self.sip_server.host}:#{self.password}" )
      )
      if ! subscriber
        errors.add( :base, I18n.t(:subscriber_not_updated))
      end
    else
      create_subscriber()
    end
  end
  
  def delete_subscriber()
    if (! self.sip_proxy_id_was.nil?) \
    && (sip_proxy = SipProxy.find_by_id( self.sip_proxy_id_was)) \
    && (sip_proxy.is_local)
      subscriber_delete = Subscriber.find_by_username( self.auth_name_was )
      if subscriber_delete
        if ! subscriber_delete.destroy
          errors.add( :base, I18n.t(:subscriber_not_deleted))
        end
      end
    end
  end
  
end

app/controllers/sip_accounts_controller.rb
class SipAccountsController < ApplicationController
  
  before_filter :authenticate_user!
  
  # https://github.com/ryanb/cancan/wiki/authorizing-controller-actions
  load_and_authorize_resource
  
  
  before_filter { |controller|
    @sip_servers  = SipServer .accessible_by( current_ability, :index ).order([ :host ])
    @sip_proxies  = SipProxy  .accessible_by( current_ability, :index ).order([ :host ])
    @voicemail_servers = VoicemailServer .accessible_by( current_ability, :index ).order([ :host ])
    @users        = User      .accessible_by( current_ability, :index ).order([ :sn, :gn, :username ]).keep_if{ |u| Ability.new(u).can?(:have, SipAccount) }
    @num_users    = User      .accessible_by( current_ability, :index ).count
  }
  
  # GET /sip_accounts
  # GET /sip_accounts.xml
  def index
    @sip_accounts = SipAccount.accessible_by( current_ability, :index ).all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sip_accounts }
    end
  end
  
  # GET /sip_accounts/1
  # GET /sip_accounts/1.xml
  def show
    @sip_account = SipAccount.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sip_account }
    end
  end
  
  # GET /sip_accounts/new
  # GET /sip_accounts/new.xml
  def new
    @sip_account                      = SipAccount.new
    @sip_account.phone_id             = params[:phone_id]
    @sip_account.user_id              = params[:user_id]
    @sip_account.sip_server_id        = params[:sip_server_id]
    @sip_account.sip_proxy_id         = params[:sip_proxy_id]
    @sip_account.voicemail_server_id  = params[:voicemail_server_id]
    @sip_account.auth_name            = SecureRandom.hex(10)
    @sip_account.password             = SecureRandom.hex(15)
    
    if SipServer.count == 1
      @sip_account.sip_server = SipServer.accessible_by( current_ability, :index ).first
    end
    if SipProxy.count == 1
      @sip_account.sip_proxy  = SipProxy.accessible_by( current_ability, :index ).first
      @sip_account.realm      = SipProxy.accessible_by( current_ability, :index ).first.try(:host)
    end
    if VoicemailServer.count == 1
      @sip_account.voicemail_server = VoicemailServer.accessible_by( current_ability, :index ).first
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sip_account }
    end
  end
  
  # GET /sip_accounts/1/edit
  def edit
    @sip_account = SipAccount.find(params[:id])
  end
  
  # POST /sip_accounts
  # POST /sip_accounts.xml
  def create
    @sip_account = SipAccount.new(params[:sip_account])
    
    respond_to do |format|
      if @sip_account.save
        format.html { redirect_to(@sip_account, :notice => t(:sip_account_created)) }
        format.xml  { render :xml => @sip_account, :status => :created, :location => @sip_account }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sip_account.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /sip_accounts/1
  # PUT /sip_accounts/1.xml
  def update
    @sip_account = SipAccount.find(params[:id])
    
    respond_to do |format|
      if @sip_account.update_attributes(params[:sip_account])
        format.html { redirect_to(@sip_account, :notice => t(:sip_account_updated)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sip_account.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /sip_accounts/1
  # DELETE /sip_accounts/1.xml
  def destroy
    @sip_account = SipAccount.find(params[:id])
    @sip_account.destroy
    
    respond_to do |format|
      format.html { redirect_to(sip_accounts_url) }
      format.xml  { head :ok }
    end
  end
  
  def confirm_destroy
    @sip_account = SipAccount.find(params[:id])
  end
  
end

app/helpers/sip_accounts_helper.rb
module SipAccountsHelper
end

app/views/sip_accounts/_form.html.erb
<%= simple_form_for( @sip_account ) { |f| %>
	<%= f.error_messages %>
	
	<%= f.input :user do %>
		<%= f.select( :user_id,
			@users.collect {|r| [ r.to_display, r.id ] },
			{ :include_blank => true, :selected => @sip_account.user_id }
		) %>
	<% end %>
	
	<%= f.input :caller_name %>
	<%= f.input :auth_name, :input_html => { :readonly => ! @sip_account.auth_name.blank? } %>
	<%= f.input :password, :as => :password %>
	<%= f.input :realm %>
	
	<%= f.input :sip_server do %>
		<%= f.select( :sip_server_id,
			@sip_servers.collect {|r| [ "#{r.host}#{r.port ? (':' + r.port.to_s) : ''} (ID #{r.id})", r.id ] },
			{ :include_blank => true, :selected => @sip_account.sip_server_id }
		) %>
	<% end %>
	
	<%= f.input :sip_proxy do %>
		<%= f.select( :sip_proxy_id,
			@sip_proxies.collect {|r| [ "#{r.host}#{r.port ? (':' + r.port.to_s) : ''} (ID #{r.id})", r.id ] },
			{ :include_blank => true, :selected => @sip_account.sip_proxy_id }
		) %>
	<% end %>
	
	<%= f.input :voicemail_server do %>
		<%= f.select( :voicemail_server_id,
			@voicemail_servers.collect {|r| [ "#{r.host}#{r.port ? (':' + r.port.to_s) : ''} (ID #{r.id})", r.id ] },
			{ :include_blank => true, :selected => @sip_account.voicemail_server_id }
		) %>
	<% end %>
	
	<%= f.input :voicemail_pin, :as => :password %>
	<%= f.association :phone, :label_method => :mac_address %>  
	
	<%= f.button :submit %>
<% } %>

app/views/sip_accounts/_show.html.erb
<div class="simple_form_show">

<p>
  <b>User:</b>
  <% if @sip_account.user %>
    <%= @sip_account.user.to_display %>
  <% end %>
</p>

<p>
  <b><%= t(:auth_name) %>:</b>
  <%= @sip_account.auth_name %>
</p>

<p>
  <b><%= t(:password) %>:</b>
  <%= @sip_account.password %>
</p>

<p>
  <b><%= t(:realm) %>:</b>
  <%= @sip_account.realm %>
</p>

<p>
  <b><%= t(:extensions) %>:</b>
  <% @sip_account.extensions.each do |extension| %>
    <%= link_to "#{extension.extension}", sip_account_extension_path( @sip_account, extension ) %>,
  <% end %>
</p>

<p>
  <b><%= t(:caller_name) %>:</b>
  <%= @sip_account.caller_name %>
</p>

<p>
  <b><%= t(:sip_server) %>:</b>
  <% if @sip_account.sip_server %>
    <%= "#{@sip_account.sip_server.host}#{@sip_account.sip_server.port ? (':' + @sip_account.sip_server.port.to_s) : ''} (ID #{@sip_account.sip_server.id})" %>
  <% end %>
</p>

<p>
  <b><%= t(:sip_proxy) %>:</b>
  <% if @sip_account.sip_proxy %>
    <%= "#{@sip_account.sip_proxy.host}#{@sip_account.sip_proxy.port ? (':' + @sip_account.sip_proxy.port.to_s) : ''} (ID #{@sip_account.sip_proxy.id})" %>
  <% end %>
</p>

<p>
  <b><%= t(:voicemail_server) %>:</b>
  <% if @sip_account.voicemail_server %>
    <%= "#{@sip_account.voicemail_server.host}#{@sip_account.voicemail_server.port ? (':' + @sip_account.voicemail_server.port.to_s) : ''} (ID #{@sip_account.voicemail_server.id})" %>
  <% end %>
</p>

<p>
  <b><%= t(:sip_phone) %>:</b>
  <% if @sip_account.phone %>
    <%= "#{@sip_account.phone.mac_address} (ID #{@sip_account.phone.id})" %>
  <% end %>
</p>

<p>
  <b><%= t(:registered) %>:</b>
  <%= @sip_account.registered? ? t(:yes_lowercase) : t(:no_lowercase) %>
</p>

</div>

app/views/sip_accounts/_table_of_sip_accounts.html.erb
<table>
	<tr>
		<% if ! current_page?('SipAccountsController#index') %>
		<th><%= t(:user) %></th>
		<th><%= t(:auth_name) %></th>
		<% end %>
		
		<th><%= t(:caller_name) %></th>
		<th><%= t(:extensions) %></th>
		
		<% if params[:controller] == 'sip_accounts' %>
		<th><%= t(:sip_phone) %></th>
		<% end %>
		
		<th><%= t(:registered) %></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

<% @sip_accounts.each do |sip_account| %>
	<tr>
		<% if ! current_page?('SipAccountsController#index') %>
		<td>
			<% if sip_account.user %>
				<%= sip_account.user.to_display %>
			<% else %>
				-
			<% end %>
		</td>
		<td><%= sip_account.auth_name %></td>
		<% end %>
		
		<td><%= sip_account.caller_name %></td>
		<td><%
			sip_account_extensions = sip_account.extensions.accessible_by( current_ability, :show )
			if sip_account_extensions
			%>
				<% sip_account_extensions.each do |extension| %>
					<%= link_to extension.extension, sip_account_extension_path(sip_account, extension) %><%= ', ' if extension != sip_account_extensions.last %>
				<% end %>
			<% end %>
		</td>
		
		<% if params[:controller] == 'sip_accounts' %>
		<td>
			<% if sip_account.try(:phone) %>
				<%= sip_account.phone.phone_model.name %><br />
				MAC: <%= link_to sip_account.phone.mac_address_to_display, sip_account.phone %><br />
				<%= "IP: #{sip_account.phone.ip_address}" if ! sip_account.phone.ip_address.blank? %>
			<% end %>
		</td>
		<% end %>
		
		<td class="<%= sip_account.registered? ? 'status_yes' : 'status_no' %>"><%= sip_account.registered? ? t(:yes_lowercase) : t(:no_lowercase) %></td>
		<td><%= link_to t(:show)    ,                                   sip_account %></td>
		<td><%= link_to t(:edit)    ,            edit_sip_account_path( sip_account ) %></td>
		<td><%= link_to t(:destroy) , confirm_destroy_sip_account_path( sip_account ) if can?( :destroy, sip_account ) %></td>
	</tr>
<% end %>
</table>

app/views/sip_accounts/confirm_destroy.html.erb
<%= simple_form_for( @sip_account, :html => { :method => :delete } ) do |f| %>
	<%= f.error_messages %>
	<h2><%= t(:confirm_destroy_record, :model_name => t("activerecord.models.sip_account"))%></h2>
	<%= render 'show' %>
	<%= f.button :submit, t(:delete) if can?( :destroy, @sip_account ) %>
	<%= link_to t(:cancel), sip_accounts_path if can?( :index, SipAccount ) %>
<% end %>

app/views/sip_accounts/edit.html.erb
<h1><%= t(:editing_sip_account) %></h1>

<%= render 'form' %>

<%= link_to t(:show), @sip_account %> |
<%= link_to t(:Go_to_list), sip_accounts_path %>

app/views/sip_accounts/index.html.erb
<% page_title t(:listing_sip_accounts) %>
<h1><%= t(:listing_sip_accounts) %></h1>

<%= render :partial => 'table_of_sip_accounts', :locals => {:sip_accounts => @sip_accounts} %>

<br />

<%= link_to t(:new_sip_account), new_sip_account_path %>

app/views/sip_accounts/new.html.erb
<h1><%= t(:new_sip_account) %></h1>

<%= render 'form' %>

<%= link_to t(:Go_to_list), sip_accounts_path %>

app/views/sip_accounts/show.html.erb
<% page_title "#{t(:sip_account)} #{@sip_account.auth_name}" %>

<div class="simple_form_show">

<p>
  <b>User:</b>
  <% if @sip_account.user %>
    <%= @sip_account.user.to_display %>
  <% end %>
</p>

<p>
  <b><%= t(:auth_name) %>:</b>
  <%= @sip_account.auth_name %>
</p>

<p>
  <b><%= t(:password) %>:</b>
  <%= @sip_account.password %>
</p>

<p>
  <b><%= t(:realm) %>:</b>
  <%= @sip_account.realm %>
</p>

<p>
  <b><%= t(:extensions) %>:</b>
  <% @sip_account.extensions.each do |extension| %>
    <%= link_to "#{extension.extension}", sip_account_extension_path( @sip_account, extension ) %>,
  <% end %>
  <%= link_to t(:new_extension), new_sip_account_extension_path( @sip_account, {:destination => @sip_account.auth_name}) %>
</p>

<% if @sip_account.extensions.count == 0 %>
  <div class="noticebox">
    <%= t(:sip_account_need_to_create_extension) %>
  </div>
<% end %>

<p>
  <b><%= t(:caller_name) %>:</b>
  <%= @sip_account.caller_name %>
</p>

<p>
  <b><%= t(:sip_server) %>:</b>
  <% if @sip_account.sip_server %>
    <%= "#{@sip_account.sip_server.host}#{@sip_account.sip_server.port ? (':' + @sip_account.sip_server.port.to_s) : ''} (ID #{@sip_account.sip_server.id})" %>
  <% end %>
</p>

<p>
  <b><%= t(:sip_proxy) %>:</b>
  <% if @sip_account.sip_proxy %>
    <%= "#{@sip_account.sip_proxy.host}#{@sip_account.sip_proxy.port ? (':' + @sip_account.sip_proxy.port.to_s) : ''} (ID #{@sip_account.sip_proxy.id})" %>
  <% end %>
</p>

<p>
  <b><%= t(:voicemail_server) %>:</b>
  <% if @sip_account.voicemail_server %>
    <%= "#{@sip_account.voicemail_server.host}#{@sip_account.voicemail_server.port ? (':' + @sip_account.voicemail_server.port.to_s) : ''} (ID #{@sip_account.voicemail_server.id})" %>
  <% end %>
</p>

<p>
  <b><%= t(:sip_phone) %>:</b>
  <% if @sip_account.phone %>
    <%= "#{@sip_account.phone.mac_address} (ID #{@sip_account.phone.id})" %>
  <% end %>
</p>

<p>
  <b><%= t(:registered) %>:</b>
  <%= @sip_account.registered? ? t(:yes_lowercase) : t(:no_lowercase) %>
</p>

</div>

<%= link_to t(:edit), edit_sip_account_path(@sip_account) %> |
<%= link_to t(:Go_to_list), sip_accounts_path %>