config/routes.rb
Gemeinschaft4::Application.routes.draw do
	
  	resources :ldap_import_sessions

	resources :network_settings
	
	resources :configurations
	
	resources :global_contacts do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :personal_contacts do
		member do
			get 'confirm_destroy'
		end
	end
		
	resources :call_logs do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :call_queues do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :call_forwards do  #OPTIMIZE Nest this inside sip_accounts and adjust the views accordingly.
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :conferences do
		member do
			get 'confirm_destroy'
		end
	end
	
	get "setup/index"  #OPTIMIZE Is this route being used?
	get "setup/create"  #OPTIMIZE Is this route being used?
	get "setup/new"  #OPTIMIZE Is this route being used?
	
	match '/auth/:provider/callback' => 'authentications#create'
	resources :authentications      , :only => [ :index, :create, :destroy ]
	
	devise_for :users, :controllers => {
		:sessions   => 'devise/sessions',
		:passwords  => 'passwords',
	}
	
	resources :sip_accounts do
		resources :extensions
	end
	resources :conferences do
		resources :extensions
	end
	resources :call_queues do
		resources :extensions
	end
	resources :backups, :only => [ :index, :create, :update, :show, :destroy, :new ]
	
	resources :sip_servers          , :only => [ :index, :show, :new, :create, :destroy ] do
		member do
			get 'confirm_destroy'
		end
	end
	resources :sip_proxies          , :only => [ :index, :show, :new, :create, :destroy ] do
		member do
			get 'confirm_destroy'
		end
	end
	resources :nodes                , :only => [ :index, :show ] # for now
	resources :voicemail_servers do
		member do
			get 'confirm_destroy'
		end
	end	
	
	resources :extensions do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :admin                , :only => [ :index ]
	resources :cdrs                 , :only => [ :index ]
	resources :kamailio             , :only => [ :index ], :format => 'txt'  #OPTIMIZE Is this route being used?
  
  match '/help',
		:via        => [ :get ],
		:controller => :home,
		:action     => 'help'

	match '/admin/help',
		:via        => [ :get ],
		:controller => :admin,
		:action     => 'help'
	
	match '/admin/shutdown',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :shutdown
	
	match '/admin/reboot',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :reboot
	
	match '/admin/confirm_reboot',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :confirm_reboot
	
	match '/admin/confirm_shutdown',
		:via        => [ :get ],
		:controller => :admin,
		:action     => :confirm_shutdown
	
	match '/freeswitch-directory-entries/search',
		:via        => [ :get, :post ],
		:controller => :freeswitch_directory_entries,
		:action     => 'search',
		:format     => :'xml'
	
	match '/freeswitch-call-processing/actions((.:subfmt).:format)',
		:via        => [ :get, :post ],
		:controller => :freeswitch_call_processing,
		:action     => 'actions',
		:defaults    => { :format => :'xml', :subfmt => nil },
		:constraints => { :format => /[a-z0-9]+/, :subfmt => /[a-z0-9]+/ }
	
	match '/freeswitch-configuration/freeswitch',
		:via        => [ :get, :post ],
		:controller => :freeswitch_configuration,
		:action     => 'load',
		:format     => :'xml'
	
	resources :dialplan_routes, :path => 'dialplan-routes' do
		member do
			post :move_up
			post :move_down
			post :move_to_top
			post :move_to_bottom
			get 'confirm_destroy'
		end
		collection do
			get  :test
			post :test
		end
	end
	
	resources :dialplan_patterns, :path => 'dialplan-patterns' do
		member do
			get 'confirm_destroy'
		end
	end
	
	namespace :admin do
		resources :wizard_phone_and_user, :only => [:new, :create]
		resources :users do
			member do
				get 'confirm_destroy'
			end
		end
		resources :setup  #OPTIMIZE Do we need a full resource or just an index?
	end
	
	match '/admin/mail_configuration',
		:via        => [ :get ],
		:controller => 'admin/mail_configuration',
		:action     => :edit
	
	match '/admin/mail_configuration',
		:via        => [ :post ],
		:controller => 'admin/mail_configuration',
		:action     => :create
	
	match '/admin/mail_configuration/show',
		:via        => [ :get ],
		:controller => 'admin/mail_configuration',
		:action     => :show
	
	resources :reboot_requests, :only => [:index, :show, :create, :new ]  #OPTIMIZE Is this route being used?
	
	resources :manufacturer_snom    , :only => [ :index ]
	resources :manufacturer_aastra  , :only => [ :index ]  #OPTIMIZE Is this route being used?
	resources :manufacturer_tiptel  , :only => [ :index ]  #OPTIMIZE Is this route being used?
	
	match '/manufacturer_snom/:mac_address/:action',
		:via        => [ :get, :post ],
		:controller => :manufacturer_snom,
		:format     => :'xml'
	
	match '/manufacturer_snom/:mac_address/:sip_account/:action',
		:via        => [ :get, :post ],
		:controller => :manufacturer_snom,
		:format     => :'xml'
	
	match 'settings-:mac_address' => 'manufacturer_snom#show',
		:format => 'xml',
		:constraints => { :mac_address => /000413.*/ }
	
	match 'freeswitch-missed-call-:uuid' => 'freeswitch_call_log#set_missed_call'
	resources :freeswitch_call_log    , :only => [ :set_missed_call ]
	
	resources :provisioning_log_entries, :only => [ :index, :show ]  #OPTIMIZE Is this route being used?
	resources :phone_model_mac_addresses  #OPTIMIZE Is this route being used?
	match 'phones/:id/reboot' => 'phones#reboot', :as => :phone_reboot
	
	
	resources :phones do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :phones do
		resources :sip_accounts  #OPTIMIZE Is it still useful to nest sip_accounts in phones?
	end
	
	resources :sip_accounts do
		resources :phone_keys  #OPTIMIZE Is this route being used?
	end
	
	resources :sip_accounts do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :codecs  #OPTIMIZE Is this route being used?
	
	resources :sip_account_codecs  #OPTIMIZE Is this route being used?
	
	resources :phone_key_function_definitions  #OPTIMIZE Is this route being used?
	
	resources :phone_model_keys  #OPTIMIZE Is this route being used?
	
	resources :manufacturers do
		resources :phone_models
	end
	
	resources :phone_models do
		resources :phones
	end
	
	resources :fax_documents do
		member do
			get 'confirm_destroy'
			get 'number'
			put 'transfer'
			post 'update'
		end
	end
	
	resources :voicemails do
		member do
			get 'confirm_destroy'
		end
	end
	
	resources :sip_gateways, :path => 'gateways' do
		member do
			get 'confirm_destroy'
		end
	end
	
	match 'pin_change',
		:via        => [ :get ],
		:controller => :pin_change,
		:action     => :edit
	
	match 'pin_change',
		:via        => [ :post ],
		:controller => :pin_change,
		:action     => :update
	
	
	
	
	
	
	
	
	
	
	root :to => 'home#index'
	
	
end

app/models/voicemail.rb
class Voicemail 
	def self.find(none)
	end
end

app/controllers/voicemails_controller.rb
class VoicemailsController < ApplicationController
	
	before_filter :authenticate_user!
	
	# https://github.com/ryanb/cancan/wiki/authorizing-controller-actions
	load_and_authorize_resource
	
	
	before_filter { |controller|
		require 'xml_rpc'
	}
	
	def index
		sip_accounts = current_user.sip_accounts.all
		@voicemails = []
		@voicemail_errors = []
		
		if sip_accounts
			sip_accounts.each { |sip_account|
				next if ! sip_account.voicemail_server
				sip_acct_voicemails = XmlRpc::voicemails_get( sip_account.auth_name, sip_account.voicemail_server.host )
				
				if ! sip_acct_voicemails
					@voicemail_errors << t( :error_retrieving_voicemail_list, :name => sip_account.to_display )
				elsif sip_acct_voicemails
					if (sip_acct_voicemails.class == Array)
						@voicemails = @voicemails.concat( sip_acct_voicemails )
					end
				end
			}
		end
		
		@voicemails.each { |voicemail_message|
			voicemail_details = XmlRpc::voicemail_get_details( voicemail_message['username'], voicemail_message['domain'], voicemail_message['uuid'] )
			if (voicemail_details && voicemail_details.key?('VM-Message-Duration'))
				voicemail_message['duration'] = voicemail_details['VM-Message-Duration']
			else
				@voicemail_errors << t( :error_retrieving_voicemail, :name => voicemail_message['uuid'] )
				voicemail_message['duration'] = 0
			end
		}
				
		respond_to do |format|
			format.html
			format.xml { render :xml => @voicemails }
		end
	end
	
	def show
		@voicemail_errors = []
		
		if (params[:id] && params[:account])
			uuid = params[:id]
			sip_account = current_user.sip_accounts.where( :auth_name => params[:account] ).first
		end
		
		if sip_account
			@auth_name = sip_account.auth_name
			@sip_account_display = sip_account.to_display
			
			if sip_account.voicemail_server
				@voicemail = XmlRpc::voicemail_get_details( @auth_name, sip_account.voicemail_server.host, uuid )
				if @voicemail && ! @voicemail['VM-Message-UUID']
					@voicemail = false
				end
			else
				@voicemail = false
			end
			
			if ! @voicemail
				@voicemail_errors << t(:error_retrieving_voicemail, :name => uuid)
			end
		end
		
		respond_to do |format|
			format.html
			format.xml  { render :xml => @voicemail }
			format.wav { 
				if File.exist?(@voicemail['VM-Message-File-Path'])
					send_file( @voicemail['VM-Message-File-Path'],
						:type => "audio/x-wav", 
						:filename => File.basename(@voicemail['VM-Message-File-Path'])
					)
				else
					render(
						:status => 404,
						:layout => false,
						:content_type => 'text/plain',
						:text => "<!-- File not found. -->",
					)
				end
			}
		end
	end
	
	def destroy
		if (params[:id] && params[:account])
			uuid = params[:id]
			sip_account = current_user.sip_accounts.where( :auth_name => params[:account] ).first
		end
		
		if sip_account
			@auth_name = sip_account.auth_name
			if sip_account.voicemail_server
				@voicemail = XmlRpc::voicemail_delete( @auth_name, sip_account.voicemail_server.host, uuid )
			else
				@voicemail = false
			end
		end
		
		respond_to do |format|
			format.html { redirect_to( voicemails_url ) }
			format.xml  { head :ok }
		end
	end
	
	def confirm_destroy
		@voicemail_id = params[:id]
		@sip_account = params[:account]
	end
end

app/views/voicemails/_show.html.erb
<% if @voicemail %>
<div class="simple_form_show">

<p>
  <b><%= t(:sip_account) %>:</b>
  <%= @sip_account_display %>
</p>

<p>
  <b><%= t(:folder) %>:</b>
  <%= @voicemail['VM-Message-Folder'] %>
</p>

<p>
  <b><%= t(:received) %>:</b>
  <%
  if @voicemail['VM-Message-Received-Epoch']
    %><%=
      l( Time.at( @voicemail['VM-Message-Received-Epoch'].to_i ).localtime, :format => :short )
    %><%
    #OPTIMIZE The date format is missing the year. The time format is missing the timezone.
  end
  %>
</p>

<p>
  <b><%= t(:read) %>:</b>
  <%
    if @voicemail['VM-Message-Read-Epoch']
      %><%= (
        (@voicemail['VM-Message-Read-Epoch'].to_i > 0) \
        ? l( Time.at( @voicemail['VM-Message-Read-Epoch'].to_i ).localtime, :format => :short ) \
        : t(:no_lowercase)
      ) %><%
    end
  %>
</p>

<p>
  <b><%= t(:vm_caller) %>:</b>
  <%= @voicemail['VM-Message-Caller-Number'] %>
</p>

<p>
  <b><%= t(:caller_name) %>:</b>
  <%= @voicemail['VM-Message-Caller-Name'] %>
</p>

<p>
  <b><%= t(:duration) %>:</b>
  <%
    if @voicemail['VM-Message-Duration']
      %><%= @voicemail['VM-Message-Duration'].to_i %> s<%
    end
  %>
</p>

<p>
  <b><%= t(:forwarded_by) %>:</b>
  <%= @voicemail['VM-Message-Forwarded-By'] %>
</p>

<p>
  <b><%= t(:vm_priority) %>:</b>
  <%
    if @voicemail['VM-Message-Read-Flags']
      %><%=
        case @voicemail['VM-Message-Read-Flags']
          when 'B_NORMAL'  ; t('vm_prio.B_NORMAL')
          when 'A_URGENT'  ; t('vm_prio.A_URGENT')
          else             ; @voicemail['VM-Message-Read-Flags']
        end
      %><%
    end
  %>
</p>

</div>
<% end %>

app/views/voicemails/confirm_destroy.html.erb
<h2><%= t(:confirm_destroy_record, :model_name => t(:voicemail))%></h2>
<%= button_to  t(:destroy) , voicemail_path( :id => @voicemail_id, :account => @sip_account ), :method => :delete %>
<%= link_to t(:cancel), voicemails_path if can?( :index, Voicemail ) %>

app/views/voicemails/index.html.erb
<%
if @voicemail_errors && @voicemail_errors.count > 0
	@voicemail_errors.each { |error|
		%><div class="noticebox"><%= error %></div><%
	}
end
%>


<h1><%= t(:listing_voicemails) %> (<%= @voicemails.try(:count) %>)</h1>

<table>
  <tr>
    <th><%= t(:sip_account) %></th>
    <th><%= t(:folder) %></th>
    <th><%= t(:date_date) %></th>
    <th colspan="2"><%= t(:from).titleize %></th>
    <th><%= t(:duration) %></th>
    <th><%= t(:status) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% if ! @voicemails.empty? %>
<% @voicemails.each do |vm_msg| %>
  <tr>
    <td><%= vm_msg['username'] %></td>
    <td><%= vm_msg['folder'] %></td>
    <td><%= l( Time.at( vm_msg['created_epoch'].to_i ).localtime, :format => :short )
      #OPTIMIZE The date format is missing the year. The time format is missing the timezone.
    %></td>
    <td><%= vm_msg['cid_number'] %></td>
    <td><%= vm_msg['cid_name'] %></td>
    <td><%= vm_msg['duration'] %></td>
    <td><%= vm_msg['read_epoch'].to_i > 0 ? t(:read) : t(:unread) %></td>
    <td><%= File.exist?( vm_msg['path'] ) ? \
      (link_to 'Wav', voicemail_path( vm_msg['uuid'], :account => vm_msg['username'], \
      :format => 'wav' )) : ''
    %></td>
    <td><%= link_to t(:show)    ,                 voicemail_path( :id => vm_msg['uuid'], :account => vm_msg['username'] ) %></td>
    <td><%= link_to t(:destroy) , confirm_destroy_voicemail_path( :id => vm_msg['uuid'], :account => vm_msg['username'] ) if can?( :destroy, Voicemail ) %></td>
  </tr>
<% end %>
<% end %>
</table>

app/views/voicemails/show.html.erb
<%
if @voicemail_errors && @voicemail_errors.count > 0
	@voicemail_errors.each { |error|
		%><div class="noticebox"><%= error %></div><%
	}
end
%>


<h1><%= t(:voicemail) %></h1>
<%= render 'show' %>
<%= link_to t(:Go_to_list), voicemails_path %>